---
- name: Example name
  hosts: example_group
  become: yes

  vars:
    example_var:
      - thiago
      - matheus
      - leo

  tasks:
    - name: install piper # (optional)
      apt: # module name
        name:
          - piper
          - muon
          - unrar